# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Orderinfo_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1097, 607)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/resource/info_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 1071, 571))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.order_id = QtWidgets.QLineEdit(self.layoutWidget)
        self.order_id.setFocusPolicy(QtCore.Qt.NoFocus)
        self.order_id.setObjectName("order_id")
        self.horizontalLayout.addWidget(self.order_id)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.supplier_id = QtWidgets.QLineEdit(self.layoutWidget)
        self.supplier_id.setFocusPolicy(QtCore.Qt.NoFocus)
        self.supplier_id.setObjectName("supplier_id")
        self.horizontalLayout.addWidget(self.supplier_id)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.supplier_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.supplier_name.setFocusPolicy(QtCore.Qt.NoFocus)
        self.supplier_name.setObjectName("supplier_name")
        self.horizontalLayout.addWidget(self.supplier_name)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.supplier_add = QtWidgets.QLineEdit(self.layoutWidget)
        self.supplier_add.setFocusPolicy(QtCore.Qt.NoFocus)
        self.supplier_add.setObjectName("supplier_add")
        self.horizontalLayout.addWidget(self.supplier_add)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.supplier_contact = QtWidgets.QLineEdit(self.layoutWidget)
        self.supplier_contact.setFocusPolicy(QtCore.Qt.NoFocus)
        self.supplier_contact.setObjectName("supplier_contact")
        self.horizontalLayout_3.addWidget(self.supplier_contact)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.supplier_tel = QtWidgets.QLineEdit(self.layoutWidget)
        self.supplier_tel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.supplier_tel.setPlaceholderText("")
        self.supplier_tel.setObjectName("supplier_tel")
        self.horizontalLayout_3.addWidget(self.supplier_tel)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.purchase_people = QtWidgets.QLineEdit(self.layoutWidget)
        self.purchase_people.setFocusPolicy(QtCore.Qt.NoFocus)
        self.purchase_people.setObjectName("purchase_people")
        self.horizontalLayout_3.addWidget(self.purchase_people)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.order_date = QtWidgets.QLineEdit(self.layoutWidget)
        self.order_date.setFocusPolicy(QtCore.Qt.NoFocus)
        self.order_date.setObjectName("order_date")
        self.horizontalLayout_3.addWidget(self.order_date)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.table_order = QtWidgets.QTableWidget(self.layoutWidget)
        self.table_order.setStyleSheet("QHeaderView::section {background-color:#008CBA ; /* 蓝色 */\n"
"                                                                color: WHITE;\n"
"                                                                };\n"
"                                                                text-align : center;")
        self.table_order.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_order.setObjectName("table_order")
        self.table_order.setColumnCount(8)
        self.table_order.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_order.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_order.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_order.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_order.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_order.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_order.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_order.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_order.setHorizontalHeaderItem(7, item)
        self.table_order.horizontalHeader().setCascadingSectionResizes(True)
        self.table_order.verticalHeader().setCascadingSectionResizes(True)
        self.verticalLayout.addWidget(self.table_order)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "采购单详情"))
        self.label.setText(_translate("Form", "采购单详情"))
        self.label_2.setText(_translate("Form", "订单编号："))
        self.label_3.setText(_translate("Form", "供应商编号："))
        self.label_5.setText(_translate("Form", "供应商名称："))
        self.label_4.setText(_translate("Form", "供应商地址:"))
        self.label_8.setText(_translate("Form", "供应商联系人:"))
        self.label_9.setText(_translate("Form", "联系人电话:"))
        self.label_10.setText(_translate("Form", "采购负责人:"))
        self.label_11.setText(_translate("Form", "下单时间:"))
        item = self.table_order.horizontalHeaderItem(0)
        item.setText(_translate("Form", "商品编号"))
        item = self.table_order.horizontalHeaderItem(1)
        item.setText(_translate("Form", "商品名称"))
        item = self.table_order.horizontalHeaderItem(2)
        item.setText(_translate("Form", "商品供应商"))
        item = self.table_order.horizontalHeaderItem(3)
        item.setText(_translate("Form", "采购数量"))
        item = self.table_order.horizontalHeaderItem(4)
        item.setText(_translate("Form", "商品单位"))
        item = self.table_order.horizontalHeaderItem(5)
        item.setText(_translate("Form", "商品进价/元"))
        item = self.table_order.horizontalHeaderItem(6)
        item.setText(_translate("Form", "总价/元"))
        item = self.table_order.horizontalHeaderItem(7)
        item.setText(_translate("Form", "订单状态"))

import main_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

