# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Saleinfo_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1097, 605)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/resource/info_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 1071, 571))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.sale_id = QtWidgets.QLineEdit(self.layoutWidget)
        self.sale_id.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sale_id.setObjectName("sale_id")
        self.horizontalLayout.addWidget(self.sale_id)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.customer_id = QtWidgets.QLineEdit(self.layoutWidget)
        self.customer_id.setFocusPolicy(QtCore.Qt.NoFocus)
        self.customer_id.setObjectName("customer_id")
        self.horizontalLayout.addWidget(self.customer_id)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.customer_name = QtWidgets.QLineEdit(self.layoutWidget)
        self.customer_name.setFocusPolicy(QtCore.Qt.NoFocus)
        self.customer_name.setObjectName("customer_name")
        self.horizontalLayout.addWidget(self.customer_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.customer_phone = QtWidgets.QLineEdit(self.layoutWidget)
        self.customer_phone.setFocusPolicy(QtCore.Qt.NoFocus)
        self.customer_phone.setObjectName("customer_phone")
        self.horizontalLayout_3.addWidget(self.customer_phone)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.customer_addr = QtWidgets.QLineEdit(self.layoutWidget)
        self.customer_addr.setFocusPolicy(QtCore.Qt.NoFocus)
        self.customer_addr.setPlaceholderText("")
        self.customer_addr.setObjectName("customer_addr")
        self.horizontalLayout_3.addWidget(self.customer_addr)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.sale_people = QtWidgets.QLineEdit(self.layoutWidget)
        self.sale_people.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sale_people.setObjectName("sale_people")
        self.horizontalLayout_3.addWidget(self.sale_people)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.sale_date = QtWidgets.QLineEdit(self.layoutWidget)
        self.sale_date.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sale_date.setObjectName("sale_date")
        self.horizontalLayout_3.addWidget(self.sale_date)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.table_sale = QtWidgets.QTableWidget(self.layoutWidget)
        self.table_sale.setStyleSheet("QHeaderView::section {background-color:#008CBA ; /* 蓝色 */\n"
"                                                                color: WHITE;\n"
"                                                                };\n"
"                                                                text-align : center;")
        self.table_sale.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_sale.setObjectName("table_sale")
        self.table_sale.setColumnCount(8)
        self.table_sale.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_sale.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_sale.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_sale.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_sale.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_sale.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_sale.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_sale.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_sale.setHorizontalHeaderItem(7, item)
        self.table_sale.horizontalHeader().setCascadingSectionResizes(True)
        self.table_sale.verticalHeader().setCascadingSectionResizes(True)
        self.verticalLayout.addWidget(self.table_sale)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "销售单详情"))
        self.label.setText(_translate("Form", "销售单详情"))
        self.label_2.setText(_translate("Form", "订单编号："))
        self.label_3.setText(_translate("Form", "顾客编号："))
        self.label_5.setText(_translate("Form", "顾客名称："))
        self.label_8.setText(_translate("Form", "顾客电话:"))
        self.label_9.setText(_translate("Form", "送货地址:"))
        self.label_10.setText(_translate("Form", "销售负责人:"))
        self.label_11.setText(_translate("Form", "下单时间:"))
        item = self.table_sale.horizontalHeaderItem(0)
        item.setText(_translate("Form", "商品编号"))
        item = self.table_sale.horizontalHeaderItem(1)
        item.setText(_translate("Form", "商品名称"))
        item = self.table_sale.horizontalHeaderItem(2)
        item.setText(_translate("Form", "商品供应商"))
        item = self.table_sale.horizontalHeaderItem(3)
        item.setText(_translate("Form", "销售数量"))
        item = self.table_sale.horizontalHeaderItem(4)
        item.setText(_translate("Form", "商品单位"))
        item = self.table_sale.horizontalHeaderItem(5)
        item.setText(_translate("Form", "单位售价/元"))
        item = self.table_sale.horizontalHeaderItem(6)
        item.setText(_translate("Form", "总价/元"))
        item = self.table_sale.horizontalHeaderItem(7)
        item.setText(_translate("Form", "订单状态"))

import main_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

