# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_warehouse.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1026, 750)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/resource/warehouse_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1001, 671))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.outbound = QtWidgets.QWidget()
        self.outbound.setObjectName("outbound")
        self.Bos_outbound = QtWidgets.QToolBox(self.outbound)
        self.Bos_outbound.setGeometry(QtCore.QRect(0, 0, 991, 611))
        self.Bos_outbound.setObjectName("Bos_outbound")
        self.tb_outbound = QtWidgets.QWidget()
        self.tb_outbound.setGeometry(QtCore.QRect(0, 0, 991, 541))
        self.tb_outbound.setObjectName("tb_outbound")
        self.layoutWidget1 = QtWidgets.QWidget(self.tb_outbound)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 0, 971, 531))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.outid_outbound = QtWidgets.QLineEdit(self.layoutWidget1)
        self.outid_outbound.setFocusPolicy(QtCore.Qt.NoFocus)
        self.outid_outbound.setObjectName("outid_outbound")
        self.horizontalLayout.addWidget(self.outid_outbound)
        self.related_sale_outbound = QtWidgets.QPushButton(self.layoutWidget1)
        self.related_sale_outbound.setMinimumSize(QtCore.QSize(130, 30))
        self.related_sale_outbound.setObjectName("related_sale_outbound")
        self.horizontalLayout.addWidget(self.related_sale_outbound)
        self.relatedSale_ID_outbound = QtWidgets.QLineEdit(self.layoutWidget1)
        self.relatedSale_ID_outbound.setFocusPolicy(QtCore.Qt.NoFocus)
        self.relatedSale_ID_outbound.setObjectName("relatedSale_ID_outbound")
        self.horizontalLayout.addWidget(self.relatedSale_ID_outbound)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.person_outbound = QtWidgets.QLineEdit(self.layoutWidget1)
        self.person_outbound.setFocusPolicy(QtCore.Qt.NoFocus)
        self.person_outbound.setObjectName("person_outbound")
        self.horizontalLayout_3.addWidget(self.person_outbound)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.date_outbound = QtWidgets.QLineEdit(self.layoutWidget1)
        self.date_outbound.setFocusPolicy(QtCore.Qt.NoFocus)
        self.date_outbound.setObjectName("date_outbound")
        self.horizontalLayout_3.addWidget(self.date_outbound)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.table_outbound = QtWidgets.QTableWidget(self.layoutWidget1)
        self.table_outbound.setStyleSheet("QHeaderView::section {background-color:#008CBA ; /* 蓝色 */\n"
"                                                                color: WHITE;\n"
"                                                                };\n"
"                                                                text-align : center;")
        self.table_outbound.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_outbound.setObjectName("table_outbound")
        self.table_outbound.setColumnCount(10)
        self.table_outbound.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_outbound.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_outbound.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_outbound.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_outbound.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_outbound.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_outbound.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_outbound.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_outbound.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_outbound.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_outbound.setHorizontalHeaderItem(9, item)
        self.verticalLayout.addWidget(self.table_outbound)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.outbound_submit = QtWidgets.QPushButton(self.layoutWidget1)
        self.outbound_submit.setMinimumSize(QtCore.QSize(0, 45))
        self.outbound_submit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.outbound_submit.setObjectName("outbound_submit")
        self.horizontalLayout_4.addWidget(self.outbound_submit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/resource/outboundinfo_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Bos_outbound.addItem(self.tb_outbound, icon1, "")
        self.tb_outbound_info = QtWidgets.QWidget()
        self.tb_outbound_info.setGeometry(QtCore.QRect(0, 0, 991, 541))
        self.tb_outbound_info.setObjectName("tb_outbound_info")
        self.layoutWidget2 = QtWidgets.QWidget(self.tb_outbound_info)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 0, 971, 531))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.outbound_id = QtWidgets.QLineEdit(self.layoutWidget2)
        self.outbound_id.setObjectName("outbound_id")
        self.horizontalLayout_5.addWidget(self.outbound_id)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.saleinfo_outbound = QtWidgets.QLineEdit(self.layoutWidget2)
        self.saleinfo_outbound.setObjectName("saleinfo_outbound")
        self.horizontalLayout_5.addWidget(self.saleinfo_outbound)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.time_outbound = QtWidgets.QLineEdit(self.layoutWidget2)
        self.time_outbound.setObjectName("time_outbound")
        self.horizontalLayout_5.addWidget(self.time_outbound)
        self.search_outbound = QtWidgets.QPushButton(self.layoutWidget2)
        self.search_outbound.setMinimumSize(QtCore.QSize(0, 30))
        self.search_outbound.setObjectName("search_outbound")
        self.horizontalLayout_5.addWidget(self.search_outbound)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.table_outboundinfo = QtWidgets.QTableWidget(self.layoutWidget2)
        self.table_outboundinfo.setStyleSheet("QHeaderView::section {background-color:#008CBA ; /* 蓝色 */\n"
"                                                                color: WHITE;\n"
"                                                                };\n"
"                                                                text-align : center;")
        self.table_outboundinfo.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_outboundinfo.setObjectName("table_outboundinfo")
        self.table_outboundinfo.setColumnCount(5)
        self.table_outboundinfo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_outboundinfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_outboundinfo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_outboundinfo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_outboundinfo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_outboundinfo.setHorizontalHeaderItem(4, item)
        self.verticalLayout_2.addWidget(self.table_outboundinfo)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/resource/search_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Bos_outbound.addItem(self.tb_outbound_info, icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/resource/outbound_info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.outbound, icon3, "")
        self.inbound = QtWidgets.QWidget()
        self.inbound.setObjectName("inbound")
        self.Box_inbound = QtWidgets.QToolBox(self.inbound)
        self.Box_inbound.setGeometry(QtCore.QRect(0, 0, 1031, 611))
        self.Box_inbound.setObjectName("Box_inbound")
        self.tb_inbound = QtWidgets.QWidget()
        self.tb_inbound.setGeometry(QtCore.QRect(0, 0, 1031, 576))
        self.tb_inbound.setObjectName("tb_inbound")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tb_inbound)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 10, 971, 551))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_6.addWidget(self.label_18)
        self.inbound_id_inbound = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.inbound_id_inbound.setFocusPolicy(QtCore.Qt.NoFocus)
        self.inbound_id_inbound.setObjectName("inbound_id_inbound")
        self.horizontalLayout_6.addWidget(self.inbound_id_inbound)
        self.but_purchasing_inbound = QtWidgets.QPushButton(self.layoutWidget_3)
        self.but_purchasing_inbound.setMinimumSize(QtCore.QSize(130, 30))
        self.but_purchasing_inbound.setObjectName("but_purchasing_inbound")
        self.horizontalLayout_6.addWidget(self.but_purchasing_inbound)
        self.purchasing_id = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.purchasing_id.setFocusPolicy(QtCore.Qt.NoFocus)
        self.purchasing_id.setObjectName("purchasing_id")
        self.horizontalLayout_6.addWidget(self.purchasing_id)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_6.addWidget(self.label_19)
        self.employee_name_inbound = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.employee_name_inbound.setFocusPolicy(QtCore.Qt.NoFocus)
        self.employee_name_inbound.setObjectName("employee_name_inbound")
        self.horizontalLayout_6.addWidget(self.employee_name_inbound)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_6.addWidget(self.label_20)
        self.date_inbound = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.date_inbound.setFocusPolicy(QtCore.Qt.NoFocus)
        self.date_inbound.setObjectName("date_inbound")
        self.horizontalLayout_6.addWidget(self.date_inbound)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.table_inbound = QtWidgets.QTableWidget(self.layoutWidget_3)
        self.table_inbound.setStyleSheet("QHeaderView::section {background-color:#008CBA ; /* 蓝色 */\n"
"                                                                color: WHITE;\n"
"                                                                };\n"
"                                                                text-align : center;")
        self.table_inbound.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_inbound.setObjectName("table_inbound")
        self.table_inbound.setColumnCount(9)
        self.table_inbound.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_inbound.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_inbound.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_inbound.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_inbound.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_inbound.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_inbound.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_inbound.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_inbound.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_inbound.setHorizontalHeaderItem(8, item)
        self.verticalLayout_4.addWidget(self.table_inbound)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.inbound_submit = QtWidgets.QPushButton(self.layoutWidget_3)
        self.inbound_submit.setMinimumSize(QtCore.QSize(0, 45))
        self.inbound_submit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.inbound_submit.setObjectName("inbound_submit")
        self.horizontalLayout_7.addWidget(self.inbound_submit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/resource/inboundinfo_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Box_inbound.addItem(self.tb_inbound, icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/resource/inbound_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.inbound, icon5, "")
        self.kucun = QtWidgets.QWidget()
        self.kucun.setObjectName("kucun")
        self.Box_kucun = QtWidgets.QToolBox(self.kucun)
        self.Box_kucun.setGeometry(QtCore.QRect(0, 0, 1031, 611))
        self.Box_kucun.setObjectName("Box_kucun")
        self.tb_kucun = QtWidgets.QWidget()
        self.tb_kucun.setGeometry(QtCore.QRect(0, 0, 1031, 576))
        self.tb_kucun.setObjectName("tb_kucun")
        self.layoutWidget_4 = QtWidgets.QWidget(self.tb_kucun)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 0, 971, 561))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_6.addWidget(self.label_25)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_26.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_8.addWidget(self.label_26)
        self.customer_id_kucun = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.customer_id_kucun.setMaximumSize(QtCore.QSize(200, 16777215))
        self.customer_id_kucun.setObjectName("customer_id_kucun")
        self.horizontalLayout_8.addWidget(self.customer_id_kucun)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_27.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_8.addWidget(self.label_27)
        self.customer_name_kucun = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.customer_name_kucun.setMaximumSize(QtCore.QSize(200, 16777215))
        self.customer_name_kucun.setObjectName("customer_name_kucun")
        self.horizontalLayout_8.addWidget(self.customer_name_kucun)
        self.search_kucun = QtWidgets.QPushButton(self.layoutWidget_4)
        self.search_kucun.setMinimumSize(QtCore.QSize(0, 30))
        self.search_kucun.setMaximumSize(QtCore.QSize(100, 16777215))
        self.search_kucun.setObjectName("search_kucun")
        self.horizontalLayout_8.addWidget(self.search_kucun)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.table_kucun = QtWidgets.QTableWidget(self.layoutWidget_4)
        self.table_kucun.setStyleSheet("QHeaderView::section {background-color:#008CBA ; /* 蓝色 */\n"
"                                                                color: WHITE;\n"
"                                                                };\n"
"                                                                text-align : center;")
        self.table_kucun.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_kucun.setObjectName("table_kucun")
        self.table_kucun.setColumnCount(8)
        self.table_kucun.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_kucun.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_kucun.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_kucun.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_kucun.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_kucun.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_kucun.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_kucun.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_kucun.setHorizontalHeaderItem(7, item)
        self.verticalLayout_6.addWidget(self.table_kucun)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/resource/write.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Box_kucun.addItem(self.tb_kucun, icon6, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/resource/modify_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.kucun, icon7, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(mainWindow)
        self.toolBar.setObjectName("toolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.Current_user = QtWidgets.QAction(mainWindow)
        self.Current_user.setEnabled(False)
        self.Current_user.setObjectName("Current_user")
        self.Current_department = QtWidgets.QAction(mainWindow)
        self.Current_department.setEnabled(False)
        self.Current_department.setObjectName("Current_department")
        self.exit = QtWidgets.QAction(mainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/img/resource/exit_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon8)
        self.exit.setObjectName("exit")
        self.toolBar.addAction(self.Current_user)
        self.toolBar.addAction(self.Current_department)
        self.toolBar.addAction(self.exit)

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.Bos_outbound.setCurrentIndex(0)
        self.Box_inbound.setCurrentIndex(0)
        self.Box_kucun.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "仓库部门"))
        self.label.setText(_translate("mainWindow", "出库单"))
        self.label_2.setText(_translate("mainWindow", "出库单号："))
        self.related_sale_outbound.setText(_translate("mainWindow", "关联销售单"))
        self.relatedSale_ID_outbound.setPlaceholderText(_translate("mainWindow", "关联销售单编号"))
        self.label_8.setText(_translate("mainWindow", "出库负责人："))
        self.label_9.setText(_translate("mainWindow", "出库日期："))
        item = self.table_outbound.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "商品编号"))
        item = self.table_outbound.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "商品名称"))
        item = self.table_outbound.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "商品供应商"))
        item = self.table_outbound.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "出库数量"))
        item = self.table_outbound.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "待出库数量"))
        item = self.table_outbound.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "商品库存"))
        item = self.table_outbound.horizontalHeaderItem(6)
        item.setText(_translate("mainWindow", "预计剩余库存"))
        item = self.table_outbound.horizontalHeaderItem(7)
        item.setText(_translate("mainWindow", "单位"))
        item = self.table_outbound.horizontalHeaderItem(8)
        item.setText(_translate("mainWindow", "销售单价"))
        item = self.table_outbound.horizontalHeaderItem(9)
        item.setText(_translate("mainWindow", "操作"))
        self.outbound_submit.setText(_translate("mainWindow", "提交"))
        self.Bos_outbound.setItemText(self.Bos_outbound.indexOf(self.tb_outbound), _translate("mainWindow", "出库"))
        self.label_12.setText(_translate("mainWindow", "出库单查询"))
        self.label_13.setText(_translate("mainWindow", "出库单编号："))
        self.label_14.setText(_translate("mainWindow", "销售单编号："))
        self.label_15.setText(_translate("mainWindow", "订单时间："))
        self.search_outbound.setText(_translate("mainWindow", "搜索"))
        item = self.table_outboundinfo.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "订单编号"))
        item = self.table_outboundinfo.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "顾客名称"))
        item = self.table_outboundinfo.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "负责人"))
        item = self.table_outboundinfo.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "订单日期"))
        item = self.table_outboundinfo.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "操作"))
        self.Bos_outbound.setItemText(self.Bos_outbound.indexOf(self.tb_outbound_info), _translate("mainWindow", "出库单查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.outbound), _translate("mainWindow", "出库管理"))
        self.label_17.setText(_translate("mainWindow", "入库单"))
        self.label_18.setText(_translate("mainWindow", "入库单号："))
        self.but_purchasing_inbound.setText(_translate("mainWindow", "关联采购单"))
        self.purchasing_id.setPlaceholderText(_translate("mainWindow", "关联采购单编号"))
        self.label_19.setText(_translate("mainWindow", "入库负责人："))
        self.label_20.setText(_translate("mainWindow", "入库日期："))
        item = self.table_inbound.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "商品编号"))
        item = self.table_inbound.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "商品名称"))
        item = self.table_inbound.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "商品供应商"))
        item = self.table_inbound.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "入库数量"))
        item = self.table_inbound.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "待入库数量"))
        item = self.table_inbound.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "商品库存"))
        item = self.table_inbound.horizontalHeaderItem(6)
        item.setText(_translate("mainWindow", "预计剩余库存"))
        item = self.table_inbound.horizontalHeaderItem(7)
        item.setText(_translate("mainWindow", "单位"))
        item = self.table_inbound.horizontalHeaderItem(8)
        item.setText(_translate("mainWindow", "操作"))
        self.inbound_submit.setText(_translate("mainWindow", "提交"))
        self.Box_inbound.setItemText(self.Box_inbound.indexOf(self.tb_inbound), _translate("mainWindow", "入库"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.inbound), _translate("mainWindow", "入库管理"))
        self.label_25.setText(_translate("mainWindow", "库存管理"))
        self.label_26.setText(_translate("mainWindow", "商品编号："))
        self.label_27.setText(_translate("mainWindow", "商品名称："))
        self.search_kucun.setText(_translate("mainWindow", "搜索"))
        item = self.table_kucun.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "商品编号"))
        item = self.table_kucun.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "商品名称"))
        item = self.table_kucun.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "商品单位"))
        item = self.table_kucun.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "供应商编号"))
        item = self.table_kucun.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "库存数量"))
        item = self.table_kucun.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "销售单价/元"))
        item = self.table_kucun.horizontalHeaderItem(6)
        item.setText(_translate("mainWindow", "成本单价/元"))
        item = self.table_kucun.horizontalHeaderItem(7)
        item.setText(_translate("mainWindow", "操作"))
        self.Box_kucun.setItemText(self.Box_kucun.indexOf(self.tb_kucun), _translate("mainWindow", "盘库"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.kucun), _translate("mainWindow", "库存管理"))
        self.label_16.setText(_translate("mainWindow", "北京邮电大学@卫闰朴"))
        self.toolBar.setWindowTitle(_translate("mainWindow", "toolBar"))
        self.Current_user.setText(_translate("mainWindow", "当前用户：xxxxx"))
        self.Current_user.setToolTip(_translate("mainWindow", "当前用户：xxxxx"))
        self.Current_department.setText(_translate("mainWindow", "当前部门：xxxxx"))
        self.exit.setText(_translate("mainWindow", "退出"))

import main_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

