# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_sale.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1026, 750)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/resource/sale_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1001, 661))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.sale = QtWidgets.QWidget()
        self.sale.setStyleSheet("")
        self.sale.setObjectName("sale")
        self.Bos_sale = QtWidgets.QToolBox(self.sale)
        self.Bos_sale.setGeometry(QtCore.QRect(0, 0, 991, 601))
        self.Bos_sale.setObjectName("Bos_sale")
        self.tb_sale = QtWidgets.QWidget()
        self.tb_sale.setGeometry(QtCore.QRect(0, 0, 991, 531))
        self.tb_sale.setObjectName("tb_sale")
        self.layoutWidget1 = QtWidgets.QWidget(self.tb_sale)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 0, 971, 531))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.order_id_sale = QtWidgets.QLineEdit(self.layoutWidget1)
        self.order_id_sale.setFocusPolicy(QtCore.Qt.NoFocus)
        self.order_id_sale.setObjectName("order_id_sale")
        self.horizontalLayout.addWidget(self.order_id_sale)
        self.customer_add_sale = QtWidgets.QPushButton(self.layoutWidget1)
        self.customer_add_sale.setMinimumSize(QtCore.QSize(130, 30))
        self.customer_add_sale.setObjectName("customer_add_sale")
        self.horizontalLayout.addWidget(self.customer_add_sale)
        self.customer_ID_sale = QtWidgets.QLineEdit(self.layoutWidget1)
        self.customer_ID_sale.setFocusPolicy(QtCore.Qt.NoFocus)
        self.customer_ID_sale.setObjectName("customer_ID_sale")
        self.horizontalLayout.addWidget(self.customer_ID_sale)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.customer_name_sale = QtWidgets.QLineEdit(self.layoutWidget1)
        self.customer_name_sale.setFocusPolicy(QtCore.Qt.NoFocus)
        self.customer_name_sale.setObjectName("customer_name_sale")
        self.horizontalLayout.addWidget(self.customer_name_sale)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.customer_phone_sale = QtWidgets.QLineEdit(self.layoutWidget1)
        self.customer_phone_sale.setFocusPolicy(QtCore.Qt.NoFocus)
        self.customer_phone_sale.setObjectName("customer_phone_sale")
        self.horizontalLayout_3.addWidget(self.customer_phone_sale)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.customer_address_sale = QtWidgets.QLineEdit(self.layoutWidget1)
        self.customer_address_sale.setFocusPolicy(QtCore.Qt.NoFocus)
        self.customer_address_sale.setObjectName("customer_address_sale")
        self.horizontalLayout_3.addWidget(self.customer_address_sale)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.currentUser_sale = QtWidgets.QLineEdit(self.layoutWidget1)
        self.currentUser_sale.setFocusPolicy(QtCore.Qt.NoFocus)
        self.currentUser_sale.setObjectName("currentUser_sale")
        self.horizontalLayout_3.addWidget(self.currentUser_sale)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.date_sale = QtWidgets.QLineEdit(self.layoutWidget1)
        self.date_sale.setFocusPolicy(QtCore.Qt.NoFocus)
        self.date_sale.setPlaceholderText("")
        self.date_sale.setObjectName("date_sale")
        self.horizontalLayout_3.addWidget(self.date_sale)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.table_sale = QtWidgets.QTableWidget(self.layoutWidget1)
        self.table_sale.setStyleSheet("QHeaderView::section {background-color:#008CBA ; /* 蓝色 */\n"
"                                                                color: WHITE;\n"
"                                                                };\n"
"                                                                text-align : center;")
        self.table_sale.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_sale.setObjectName("table_sale")
        self.table_sale.setColumnCount(8)
        self.table_sale.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_sale.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_sale.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_sale.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_sale.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_sale.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_sale.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_sale.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_sale.setHorizontalHeaderItem(7, item)
        self.verticalLayout.addWidget(self.table_sale)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sale_goods_add = QtWidgets.QPushButton(self.layoutWidget1)
        self.sale_goods_add.setMinimumSize(QtCore.QSize(0, 45))
        self.sale_goods_add.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sale_goods_add.setObjectName("sale_goods_add")
        self.horizontalLayout_4.addWidget(self.sale_goods_add)
        self.sale_submit = QtWidgets.QPushButton(self.layoutWidget1)
        self.sale_submit.setMinimumSize(QtCore.QSize(0, 45))
        self.sale_submit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sale_submit.setObjectName("sale_submit")
        self.horizontalLayout_4.addWidget(self.sale_submit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/resource/write.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Bos_sale.addItem(self.tb_sale, icon1, "")
        self.tb_sale_info = QtWidgets.QWidget()
        self.tb_sale_info.setGeometry(QtCore.QRect(0, 0, 991, 531))
        self.tb_sale_info.setObjectName("tb_sale_info")
        self.layoutWidget2 = QtWidgets.QWidget(self.tb_sale_info)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 0, 971, 685))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.order_id_saleinfo = QtWidgets.QLineEdit(self.layoutWidget2)
        self.order_id_saleinfo.setObjectName("order_id_saleinfo")
        self.horizontalLayout_5.addWidget(self.order_id_saleinfo)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.customer_id_saleinfo = QtWidgets.QLineEdit(self.layoutWidget2)
        self.customer_id_saleinfo.setObjectName("customer_id_saleinfo")
        self.horizontalLayout_5.addWidget(self.customer_id_saleinfo)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox)
        self.search_saleinfo = QtWidgets.QPushButton(self.layoutWidget2)
        self.search_saleinfo.setMinimumSize(QtCore.QSize(100, 30))
        self.search_saleinfo.setObjectName("search_saleinfo")
        self.horizontalLayout_5.addWidget(self.search_saleinfo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.table_saleinfo = QtWidgets.QTableWidget(self.layoutWidget2)
        self.table_saleinfo.setStyleSheet("QHeaderView::section {background-color:#008CBA ; /* 蓝色 */\n"
"                                                                color: WHITE;\n"
"                                                                };\n"
"                                                                text-align : center;")
        self.table_saleinfo.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_saleinfo.setObjectName("table_saleinfo")
        self.table_saleinfo.setColumnCount(5)
        self.table_saleinfo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_saleinfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_saleinfo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_saleinfo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_saleinfo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_saleinfo.setHorizontalHeaderItem(4, item)
        self.verticalLayout_2.addWidget(self.table_saleinfo)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/resource/saleinfo_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Bos_sale.addItem(self.tb_sale_info, icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/resource/sale_management.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.sale, icon3, "")
        self.dispatch = QtWidgets.QWidget()
        self.dispatch.setObjectName("dispatch")
        self.Box_dispatch = QtWidgets.QToolBox(self.dispatch)
        self.Box_dispatch.setGeometry(QtCore.QRect(0, 0, 1031, 601))
        self.Box_dispatch.setObjectName("Box_dispatch")
        self.tb_dispatch = QtWidgets.QWidget()
        self.tb_dispatch.setGeometry(QtCore.QRect(0, 0, 1031, 566))
        self.tb_dispatch.setObjectName("tb_dispatch")
        self.layoutWidget3 = QtWidgets.QWidget(self.tb_dispatch)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 0, 981, 571))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_6.addWidget(self.label_18)
        self.dispatch_id_dispatch = QtWidgets.QLineEdit(self.layoutWidget3)
        self.dispatch_id_dispatch.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dispatch_id_dispatch.setObjectName("dispatch_id_dispatch")
        self.horizontalLayout_6.addWidget(self.dispatch_id_dispatch)
        self.linkbutton_dispatch = QtWidgets.QPushButton(self.layoutWidget3)
        self.linkbutton_dispatch.setMinimumSize(QtCore.QSize(130, 30))
        self.linkbutton_dispatch.setObjectName("linkbutton_dispatch")
        self.horizontalLayout_6.addWidget(self.linkbutton_dispatch)
        self.outid = QtWidgets.QLineEdit(self.layoutWidget3)
        self.outid.setFocusPolicy(QtCore.Qt.NoFocus)
        self.outid.setObjectName("outid")
        self.horizontalLayout_6.addWidget(self.outid)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_6.addWidget(self.label_19)
        self.employee_name_2 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.employee_name_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.employee_name_2.setObjectName("employee_name_2")
        self.horizontalLayout_6.addWidget(self.employee_name_2)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_6.addWidget(self.label_20)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_18.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.horizontalLayout_6.addWidget(self.lineEdit_18)
        self.submit_dispatch = QtWidgets.QPushButton(self.layoutWidget3)
        self.submit_dispatch.setMinimumSize(QtCore.QSize(100, 30))
        self.submit_dispatch.setMaximumSize(QtCore.QSize(200, 16777215))
        self.submit_dispatch.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.submit_dispatch.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.submit_dispatch.setFlat(False)
        self.submit_dispatch.setObjectName("submit_dispatch")
        self.horizontalLayout_6.addWidget(self.submit_dispatch)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.table_dispatch = QtWidgets.QTableWidget(self.layoutWidget3)
        self.table_dispatch.setStyleSheet("QHeaderView::section {background-color:#008CBA ; /* 蓝色 */\n"
"                                                                color: WHITE;\n"
"                                                                };\n"
"                                                                text-align : center;")
        self.table_dispatch.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_dispatch.setObjectName("table_dispatch")
        self.table_dispatch.setColumnCount(7)
        self.table_dispatch.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_dispatch.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dispatch.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dispatch.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dispatch.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dispatch.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dispatch.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dispatch.setHorizontalHeaderItem(6, item)
        self.verticalLayout_4.addWidget(self.table_dispatch)
        self.Box_dispatch.addItem(self.tb_dispatch, icon1, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/resource/dispatch_management.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.dispatch, icon4, "")
        self.user = QtWidgets.QWidget()
        self.user.setObjectName("user")
        self.Box_user = QtWidgets.QToolBox(self.user)
        self.Box_user.setGeometry(QtCore.QRect(0, 0, 1031, 591))
        self.Box_user.setObjectName("Box_user")
        self.tb_user = QtWidgets.QWidget()
        self.tb_user.setGeometry(QtCore.QRect(0, 0, 1031, 521))
        self.tb_user.setObjectName("tb_user")
        self.layoutWidget_4 = QtWidgets.QWidget(self.tb_user)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 0, 971, 521))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_6.addWidget(self.label_25)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_26.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_8.addWidget(self.label_26)
        self.customer_id_user = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.customer_id_user.setMaximumSize(QtCore.QSize(200, 16777215))
        self.customer_id_user.setObjectName("customer_id_user")
        self.horizontalLayout_8.addWidget(self.customer_id_user)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_27.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_8.addWidget(self.label_27)
        self.customer_name_user = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.customer_name_user.setMaximumSize(QtCore.QSize(200, 16777215))
        self.customer_name_user.setObjectName("customer_name_user")
        self.horizontalLayout_8.addWidget(self.customer_name_user)
        self.search_user = QtWidgets.QPushButton(self.layoutWidget_4)
        self.search_user.setMinimumSize(QtCore.QSize(0, 30))
        self.search_user.setMaximumSize(QtCore.QSize(100, 16777215))
        self.search_user.setObjectName("search_user")
        self.horizontalLayout_8.addWidget(self.search_user)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.table_user = QtWidgets.QTableWidget(self.layoutWidget_4)
        self.table_user.setStyleSheet("QHeaderView::section {background-color:#008CBA ; /* 蓝色 */\n"
"                                                                color: WHITE;\n"
"                                                                };\n"
"                                                                text-align : center;")
        self.table_user.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_user.setObjectName("table_user")
        self.table_user.setColumnCount(5)
        self.table_user.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_user.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_user.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_user.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_user.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_user.setHorizontalHeaderItem(4, item)
        self.verticalLayout_6.addWidget(self.table_user)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/resource/customer_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Box_user.addItem(self.tb_user, icon5, "")
        self.tb_user_add = QtWidgets.QWidget()
        self.tb_user_add.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.tb_user_add.setObjectName("tb_user_add")
        self.layoutWidget4 = QtWidgets.QWidget(self.tb_user_add)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 0, 981, 531))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_28.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_7.addWidget(self.label_28)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_29.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_9.addWidget(self.label_29)
        self.customer_id_new = QtWidgets.QLineEdit(self.layoutWidget4)
        self.customer_id_new.setMaximumSize(QtCore.QSize(200, 16777215))
        self.customer_id_new.setFocusPolicy(QtCore.Qt.NoFocus)
        self.customer_id_new.setObjectName("customer_id_new")
        self.horizontalLayout_9.addWidget(self.customer_id_new)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_30.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_9.addWidget(self.label_30)
        self.customer_name_new = QtWidgets.QLineEdit(self.layoutWidget4)
        self.customer_name_new.setMaximumSize(QtCore.QSize(200, 16777215))
        self.customer_name_new.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.customer_name_new.setObjectName("customer_name_new")
        self.horizontalLayout_9.addWidget(self.customer_name_new)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_31.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_10.addWidget(self.label_31)
        self.customer_phone_new = QtWidgets.QLineEdit(self.layoutWidget4)
        self.customer_phone_new.setMaximumSize(QtCore.QSize(200, 16777215))
        self.customer_phone_new.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.customer_phone_new.setObjectName("customer_phone_new")
        self.horizontalLayout_10.addWidget(self.customer_phone_new)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_32.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_10.addWidget(self.label_32)
        self.customer_address_new = QtWidgets.QLineEdit(self.layoutWidget4)
        self.customer_address_new.setMaximumSize(QtCore.QSize(200, 16777215))
        self.customer_address_new.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.customer_address_new.setObjectName("customer_address_new")
        self.horizontalLayout_10.addWidget(self.customer_address_new)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.submit_user_add = QtWidgets.QPushButton(self.layoutWidget4)
        self.submit_user_add.setMinimumSize(QtCore.QSize(130, 30))
        self.submit_user_add.setMaximumSize(QtCore.QSize(100, 16777215))
        self.submit_user_add.setObjectName("submit_user_add")
        self.horizontalLayout_12.addWidget(self.submit_user_add)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/resource/add_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Box_user.addItem(self.tb_user_add, icon6, "")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/resource/customer_management.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.user, icon7, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(mainWindow)
        self.toolBar.setObjectName("toolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.Current_user = QtWidgets.QAction(mainWindow)
        self.Current_user.setEnabled(False)
        self.Current_user.setObjectName("Current_user")
        self.Current_department = QtWidgets.QAction(mainWindow)
        self.Current_department.setEnabled(False)
        self.Current_department.setObjectName("Current_department")
        self.exit = QtWidgets.QAction(mainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/img/resource/exit_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon8)
        self.exit.setObjectName("exit")
        self.toolBar.addAction(self.Current_user)
        self.toolBar.addAction(self.Current_department)
        self.toolBar.addAction(self.exit)

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.Bos_sale.setCurrentIndex(0)
        self.Box_dispatch.setCurrentIndex(0)
        self.Box_user.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "销售部门"))
        self.label.setText(_translate("mainWindow", "销售单"))
        self.label_2.setText(_translate("mainWindow", "订单编号："))
        self.customer_add_sale.setText(_translate("mainWindow", "添加顾客信息"))
        self.customer_ID_sale.setPlaceholderText(_translate("mainWindow", "顾客编号"))
        self.label_4.setText(_translate("mainWindow", "顾客姓名："))
        self.label_8.setText(_translate("mainWindow", "顾客电话："))
        self.label_9.setText(_translate("mainWindow", "送货地址"))
        self.label_10.setText(_translate("mainWindow", "销售负责人："))
        self.label_11.setText(_translate("mainWindow", "下单时间："))
        item = self.table_sale.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "商品编号"))
        item = self.table_sale.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "商品名称"))
        item = self.table_sale.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "商品供应商"))
        item = self.table_sale.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "销售数量"))
        item = self.table_sale.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "商品单位"))
        item = self.table_sale.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "商品售价/元"))
        item = self.table_sale.horizontalHeaderItem(6)
        item.setText(_translate("mainWindow", "总价/元"))
        item = self.table_sale.horizontalHeaderItem(7)
        item.setText(_translate("mainWindow", "操作"))
        self.sale_goods_add.setText(_translate("mainWindow", "添加商品信息"))
        self.sale_submit.setText(_translate("mainWindow", "提交"))
        self.Bos_sale.setItemText(self.Bos_sale.indexOf(self.tb_sale), _translate("mainWindow", "填写销售单"))
        self.label_12.setText(_translate("mainWindow", "销售单查询"))
        self.label_13.setText(_translate("mainWindow", "订单编号："))
        self.order_id_saleinfo.setPlaceholderText(_translate("mainWindow", "无"))
        self.label_14.setText(_translate("mainWindow", "顾客编号："))
        self.customer_id_saleinfo.setPlaceholderText(_translate("mainWindow", "无"))
        self.label_15.setText(_translate("mainWindow", "订单时间："))
        self.comboBox.setItemText(0, _translate("mainWindow", "无"))
        self.comboBox.setItemText(1, _translate("mainWindow", "三天内"))
        self.comboBox.setItemText(2, _translate("mainWindow", "一周内"))
        self.comboBox.setItemText(3, _translate("mainWindow", "一个月内"))
        self.search_saleinfo.setText(_translate("mainWindow", "搜索"))
        item = self.table_saleinfo.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "销售单编号"))
        item = self.table_saleinfo.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "顾客名称"))
        item = self.table_saleinfo.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "负责人"))
        item = self.table_saleinfo.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "订单日期"))
        item = self.table_saleinfo.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "操作"))
        self.Bos_sale.setItemText(self.Bos_sale.indexOf(self.tb_sale_info), _translate("mainWindow", "销售单查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sale), _translate("mainWindow", "销售管理"))
        self.label_17.setText(_translate("mainWindow", "发货单"))
        self.label_18.setText(_translate("mainWindow", "发货单号："))
        self.linkbutton_dispatch.setText(_translate("mainWindow", "关联出库单"))
        self.outid.setPlaceholderText(_translate("mainWindow", "关联出库单编号"))
        self.label_19.setText(_translate("mainWindow", "发货负责人："))
        self.label_20.setText(_translate("mainWindow", "发货日期："))
        self.submit_dispatch.setText(_translate("mainWindow", "提交"))
        item = self.table_dispatch.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "商品编号"))
        item = self.table_dispatch.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "商品名称"))
        item = self.table_dispatch.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "商品供应商"))
        item = self.table_dispatch.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "发货数量"))
        item = self.table_dispatch.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "商品单位"))
        item = self.table_dispatch.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "商品售价/元"))
        item = self.table_dispatch.horizontalHeaderItem(6)
        item.setText(_translate("mainWindow", "总价/元"))
        self.Box_dispatch.setItemText(self.Box_dispatch.indexOf(self.tb_dispatch), _translate("mainWindow", "填写发货单"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dispatch), _translate("mainWindow", "发货管理"))
        self.label_25.setText(_translate("mainWindow", "顾客信息"))
        self.label_26.setText(_translate("mainWindow", "顾客编号："))
        self.customer_id_user.setPlaceholderText(_translate("mainWindow", "无"))
        self.label_27.setText(_translate("mainWindow", "顾客名称："))
        self.customer_name_user.setPlaceholderText(_translate("mainWindow", "无"))
        self.search_user.setText(_translate("mainWindow", "搜索"))
        item = self.table_user.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "顾客编号"))
        item = self.table_user.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "顾客姓名"))
        item = self.table_user.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "顾客电话"))
        item = self.table_user.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "送货地址"))
        item = self.table_user.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "操作"))
        self.Box_user.setItemText(self.Box_user.indexOf(self.tb_user), _translate("mainWindow", "顾客查询"))
        self.label_28.setText(_translate("mainWindow", "添加顾客信息"))
        self.label_29.setText(_translate("mainWindow", "顾客编号："))
        self.label_30.setText(_translate("mainWindow", "顾客姓名："))
        self.label_31.setText(_translate("mainWindow", "顾客电话："))
        self.label_32.setText(_translate("mainWindow", "顾客地址："))
        self.submit_user_add.setText(_translate("mainWindow", "提交"))
        self.Box_user.setItemText(self.Box_user.indexOf(self.tb_user_add), _translate("mainWindow", "添加顾客信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.user), _translate("mainWindow", "顾客管理"))
        self.label_16.setText(_translate("mainWindow", "北京邮电大学@卫闰朴"))
        self.toolBar.setWindowTitle(_translate("mainWindow", "toolBar"))
        self.Current_user.setText(_translate("mainWindow", "当前用户：xxxxx"))
        self.Current_user.setToolTip(_translate("mainWindow", "当前用户：xxxxx"))
        self.Current_department.setText(_translate("mainWindow", "当前部门：xxxxx"))
        self.exit.setText(_translate("mainWindow", "退出"))

import main_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

