# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_purchasing.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1026, 750)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/resource/purchase_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1001, 661))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.purchasing = QtWidgets.QWidget()
        self.purchasing.setObjectName("purchasing")
        self.Box_purchasing = QtWidgets.QToolBox(self.purchasing)
        self.Box_purchasing.setGeometry(QtCore.QRect(0, 0, 991, 591))
        self.Box_purchasing.setObjectName("Box_purchasing")
        self.tb_order_2 = QtWidgets.QWidget()
        self.tb_order_2.setGeometry(QtCore.QRect(0, 0, 991, 486))
        self.tb_order_2.setObjectName("tb_order_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.tb_order_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 0, 971, 481))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.order_id_order_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.order_id_order_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.order_id_order_2.setObjectName("order_id_order_2")
        self.horizontalLayout.addWidget(self.order_id_order_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.order_date = QtWidgets.QLineEdit(self.layoutWidget1)
        self.order_date.setFocusPolicy(QtCore.Qt.NoFocus)
        self.order_date.setObjectName("order_date")
        self.horizontalLayout.addWidget(self.order_date)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.employee_name = QtWidgets.QLineEdit(self.layoutWidget1)
        self.employee_name.setFocusPolicy(QtCore.Qt.NoFocus)
        self.employee_name.setObjectName("employee_name")
        self.horizontalLayout.addWidget(self.employee_name)
        self.supplier_add = QtWidgets.QPushButton(self.layoutWidget1)
        self.supplier_add.setMinimumSize(QtCore.QSize(140, 30))
        self.supplier_add.setObjectName("supplier_add")
        self.horizontalLayout.addWidget(self.supplier_add)
        self.supplier_id = QtWidgets.QLineEdit(self.layoutWidget1)
        self.supplier_id.setFocusPolicy(QtCore.Qt.NoFocus)
        self.supplier_id.setObjectName("supplier_id")
        self.horizontalLayout.addWidget(self.supplier_id)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.supplier_name = QtWidgets.QLineEdit(self.layoutWidget1)
        self.supplier_name.setFocusPolicy(QtCore.Qt.NoFocus)
        self.supplier_name.setObjectName("supplier_name")
        self.horizontalLayout_3.addWidget(self.supplier_name)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.supplier_address = QtWidgets.QLineEdit(self.layoutWidget1)
        self.supplier_address.setFocusPolicy(QtCore.Qt.NoFocus)
        self.supplier_address.setObjectName("supplier_address")
        self.horizontalLayout_3.addWidget(self.supplier_address)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10)
        self.supplier_contact = QtWidgets.QLineEdit(self.layoutWidget1)
        self.supplier_contact.setFocusPolicy(QtCore.Qt.NoFocus)
        self.supplier_contact.setObjectName("supplier_contact")
        self.horizontalLayout_3.addWidget(self.supplier_contact)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.supplier_tel = QtWidgets.QLineEdit(self.layoutWidget1)
        self.supplier_tel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.supplier_tel.setPlaceholderText("")
        self.supplier_tel.setObjectName("supplier_tel")
        self.horizontalLayout_3.addWidget(self.supplier_tel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.table_order = QtWidgets.QTableWidget(self.layoutWidget1)
        self.table_order.setStyleSheet("QHeaderView::section {background-color:#008CBA ; /* 蓝色 */\n"
"                                                                color: WHITE;\n"
"                                                                };\n"
"                                                                text-align : center;")
        self.table_order.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_order.setObjectName("table_order")
        self.table_order.setColumnCount(7)
        self.table_order.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_order.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_order.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_order.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_order.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_order.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_order.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_order.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.table_order)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.order_goods_add = QtWidgets.QPushButton(self.layoutWidget1)
        self.order_goods_add.setMinimumSize(QtCore.QSize(0, 45))
        self.order_goods_add.setMaximumSize(QtCore.QSize(200, 16777215))
        self.order_goods_add.setObjectName("order_goods_add")
        self.horizontalLayout_4.addWidget(self.order_goods_add)
        self.order_submit = QtWidgets.QPushButton(self.layoutWidget1)
        self.order_submit.setMinimumSize(QtCore.QSize(0, 45))
        self.order_submit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.order_submit.setObjectName("order_submit")
        self.horizontalLayout_4.addWidget(self.order_submit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/resource/write.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Box_purchasing.addItem(self.tb_order_2, icon1, "")
        self.tb_order_info = QtWidgets.QWidget()
        self.tb_order_info.setGeometry(QtCore.QRect(0, 0, 991, 486))
        self.tb_order_info.setObjectName("tb_order_info")
        self.layoutWidget2 = QtWidgets.QWidget(self.tb_order_info)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 0, 971, 481))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.order_id_orderinfo = QtWidgets.QLineEdit(self.layoutWidget2)
        self.order_id_orderinfo.setObjectName("order_id_orderinfo")
        self.horizontalLayout_5.addWidget(self.order_id_orderinfo)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.supplier_id_orderinfo = QtWidgets.QLineEdit(self.layoutWidget2)
        self.supplier_id_orderinfo.setObjectName("supplier_id_orderinfo")
        self.horizontalLayout_5.addWidget(self.supplier_id_orderinfo)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.ordertime_orderinfo = QtWidgets.QComboBox(self.layoutWidget2)
        self.ordertime_orderinfo.setMinimumSize(QtCore.QSize(120, 0))
        self.ordertime_orderinfo.setObjectName("ordertime_orderinfo")
        self.ordertime_orderinfo.addItem("")
        self.ordertime_orderinfo.addItem("")
        self.ordertime_orderinfo.addItem("")
        self.ordertime_orderinfo.addItem("")
        self.horizontalLayout_5.addWidget(self.ordertime_orderinfo)
        self.search_orderinfo = QtWidgets.QPushButton(self.layoutWidget2)
        self.search_orderinfo.setObjectName("search_orderinfo")
        self.horizontalLayout_5.addWidget(self.search_orderinfo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.table_orderinfo = QtWidgets.QTableWidget(self.layoutWidget2)
        self.table_orderinfo.setStyleSheet("QHeaderView::section {background-color:#008CBA ; /* 蓝色 */\n"
"                                                                color: WHITE;\n"
"                                                                };\n"
"                                                                text-align : center;")
        self.table_orderinfo.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_orderinfo.setObjectName("table_orderinfo")
        self.table_orderinfo.setColumnCount(5)
        self.table_orderinfo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_orderinfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_orderinfo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_orderinfo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_orderinfo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_orderinfo.setHorizontalHeaderItem(4, item)
        self.verticalLayout_2.addWidget(self.table_orderinfo)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/resource/search_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Box_purchasing.addItem(self.tb_order_info, icon2, "")
        self.tb_DraftOrder = QtWidgets.QWidget()
        self.tb_DraftOrder.setGeometry(QtCore.QRect(0, 0, 991, 486))
        self.tb_DraftOrder.setObjectName("tb_DraftOrder")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tb_DraftOrder)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 0, 971, 481))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_5.addWidget(self.label_21)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_7.addWidget(self.label_22)
        self.order_id_draftOrder = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.order_id_draftOrder.setObjectName("order_id_draftOrder")
        self.horizontalLayout_7.addWidget(self.order_id_draftOrder)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_7.addWidget(self.label_23)
        self.supplier_id_draftOrder = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.supplier_id_draftOrder.setObjectName("supplier_id_draftOrder")
        self.horizontalLayout_7.addWidget(self.supplier_id_draftOrder)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_7.addWidget(self.label_24)
        self.ordertime_draftOrder = QtWidgets.QComboBox(self.layoutWidget_2)
        self.ordertime_draftOrder.setMinimumSize(QtCore.QSize(120, 0))
        self.ordertime_draftOrder.setObjectName("ordertime_draftOrder")
        self.ordertime_draftOrder.addItem("")
        self.ordertime_draftOrder.addItem("")
        self.ordertime_draftOrder.addItem("")
        self.ordertime_draftOrder.addItem("")
        self.horizontalLayout_7.addWidget(self.ordertime_draftOrder)
        self.search_draftOrder = QtWidgets.QPushButton(self.layoutWidget_2)
        self.search_draftOrder.setObjectName("search_draftOrder")
        self.horizontalLayout_7.addWidget(self.search_draftOrder)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.table_draftOrder = QtWidgets.QTableWidget(self.layoutWidget_2)
        self.table_draftOrder.setStyleSheet("QHeaderView::section {background-color:#008CBA ; /* 蓝色 */\n"
"                                                                color: WHITE;\n"
"                                                                };\n"
"                                                                text-align : center;")
        self.table_draftOrder.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_draftOrder.setObjectName("table_draftOrder")
        self.table_draftOrder.setColumnCount(8)
        self.table_draftOrder.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_draftOrder.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_draftOrder.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_draftOrder.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_draftOrder.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_draftOrder.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_draftOrder.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_draftOrder.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_draftOrder.setHorizontalHeaderItem(7, item)
        self.verticalLayout_5.addWidget(self.table_draftOrder)
        self.Box_purchasing.addItem(self.tb_DraftOrder, icon2, "")
        self.tabWidget.addTab(self.purchasing, icon, "")
        self.returns = QtWidgets.QWidget()
        self.returns.setObjectName("returns")
        self.Box_returns = QtWidgets.QToolBox(self.returns)
        self.Box_returns.setGeometry(QtCore.QRect(0, 0, 1031, 591))
        self.Box_returns.setObjectName("Box_returns")
        self.tb_returns = QtWidgets.QWidget()
        self.tb_returns.setGeometry(QtCore.QRect(0, 0, 1031, 556))
        self.tb_returns.setObjectName("tb_returns")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tb_returns)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 10, 971, 541))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_6.addWidget(self.label_18)
        self.return_id_return = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.return_id_return.setFocusPolicy(QtCore.Qt.NoFocus)
        self.return_id_return.setObjectName("return_id_return")
        self.horizontalLayout_6.addWidget(self.return_id_return)
        self.linkbutton_return = QtWidgets.QPushButton(self.layoutWidget_3)
        self.linkbutton_return.setObjectName("linkbutton_return")
        self.horizontalLayout_6.addWidget(self.linkbutton_return)
        self.order_id_2 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.order_id_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.order_id_2.setText("")
        self.order_id_2.setObjectName("order_id_2")
        self.horizontalLayout_6.addWidget(self.order_id_2)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_6.addWidget(self.label_19)
        self.employee_name_2 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.employee_name_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.employee_name_2.setObjectName("employee_name_2")
        self.horizontalLayout_6.addWidget(self.employee_name_2)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_6.addWidget(self.label_20)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_18.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.horizontalLayout_6.addWidget(self.lineEdit_18)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.table_return = QtWidgets.QTableWidget(self.layoutWidget_3)
        self.table_return.setStyleSheet("QHeaderView::section {background-color:#008CBA ; /* 蓝色 */\n"
"                                                                color: WHITE;\n"
"                                                                };\n"
"                                                                text-align : center;")
        self.table_return.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_return.setObjectName("table_return")
        self.table_return.setColumnCount(8)
        self.table_return.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_return.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_return.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_return.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_return.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_return.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_return.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_return.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_return.setHorizontalHeaderItem(7, item)
        self.verticalLayout_4.addWidget(self.table_return)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.return_button = QtWidgets.QPushButton(self.layoutWidget_3)
        self.return_button.setMinimumSize(QtCore.QSize(130, 40))
        self.return_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.return_button.setObjectName("return_button")
        self.horizontalLayout_19.addWidget(self.return_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)
        self.Box_returns.addItem(self.tb_returns, icon1, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/resource/dispatch_management.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.returns, icon3, "")
        self.goods = QtWidgets.QWidget()
        self.goods.setObjectName("goods")
        self.Box_goods = QtWidgets.QToolBox(self.goods)
        self.Box_goods.setGeometry(QtCore.QRect(0, 0, 1031, 591))
        self.Box_goods.setObjectName("Box_goods")
        self.tb_goods = QtWidgets.QWidget()
        self.tb_goods.setGeometry(QtCore.QRect(0, 0, 1031, 521))
        self.tb_goods.setObjectName("tb_goods")
        self.layoutWidget_4 = QtWidgets.QWidget(self.tb_goods)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 0, 971, 521))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_6.addWidget(self.label_25)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_26.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_8.addWidget(self.label_26)
        self.goodsid_goods = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.goodsid_goods.setMaximumSize(QtCore.QSize(200, 16777215))
        self.goodsid_goods.setObjectName("goodsid_goods")
        self.horizontalLayout_8.addWidget(self.goodsid_goods)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_27.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_8.addWidget(self.label_27)
        self.goodsname_goods = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.goodsname_goods.setMaximumSize(QtCore.QSize(200, 16777215))
        self.goodsname_goods.setObjectName("goodsname_goods")
        self.horizontalLayout_8.addWidget(self.goodsname_goods)
        self.search_goods = QtWidgets.QPushButton(self.layoutWidget_4)
        self.search_goods.setMaximumSize(QtCore.QSize(100, 16777215))
        self.search_goods.setObjectName("search_goods")
        self.horizontalLayout_8.addWidget(self.search_goods)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.table_goods = QtWidgets.QTableWidget(self.layoutWidget_4)
        self.table_goods.setStyleSheet("QHeaderView::section {background-color:#008CBA ; /* 蓝色 */\n"
"                                                                color: WHITE;\n"
"                                                                };\n"
"                                                                text-align : center;")
        self.table_goods.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_goods.setObjectName("table_goods")
        self.table_goods.setColumnCount(8)
        self.table_goods.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_goods.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_goods.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_goods.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_goods.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_goods.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_goods.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_goods.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_goods.setHorizontalHeaderItem(7, item)
        self.verticalLayout_6.addWidget(self.table_goods)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/resource/Goods_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Box_goods.addItem(self.tb_goods, icon4, "")
        self.tb_goods_add = QtWidgets.QWidget()
        self.tb_goods_add.setGeometry(QtCore.QRect(0, 0, 1031, 521))
        self.tb_goods_add.setObjectName("tb_goods_add")
        self.layoutWidget3 = QtWidgets.QWidget(self.tb_goods_add)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 0, 981, 521))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_28.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_7.addWidget(self.label_28)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_29.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_9.addWidget(self.label_29)
        self.goodsid_goods_add = QtWidgets.QLineEdit(self.layoutWidget3)
        self.goodsid_goods_add.setMaximumSize(QtCore.QSize(200, 16777215))
        self.goodsid_goods_add.setFocusPolicy(QtCore.Qt.NoFocus)
        self.goodsid_goods_add.setObjectName("goodsid_goods_add")
        self.horizontalLayout_9.addWidget(self.goodsid_goods_add)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_30.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_9.addWidget(self.label_30)
        self.goodsname_goods_add = QtWidgets.QLineEdit(self.layoutWidget3)
        self.goodsname_goods_add.setMaximumSize(QtCore.QSize(200, 16777215))
        self.goodsname_goods_add.setObjectName("goodsname_goods_add")
        self.horizontalLayout_9.addWidget(self.goodsname_goods_add)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_31.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_10.addWidget(self.label_31)
        self.stock_goods_add = QtWidgets.QLineEdit(self.layoutWidget3)
        self.stock_goods_add.setMaximumSize(QtCore.QSize(200, 16777215))
        self.stock_goods_add.setObjectName("stock_goods_add")
        self.horizontalLayout_10.addWidget(self.stock_goods_add)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_32.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_10.addWidget(self.label_32)
        self.unit_goods_add = QtWidgets.QLineEdit(self.layoutWidget3)
        self.unit_goods_add.setMaximumSize(QtCore.QSize(200, 16777215))
        self.unit_goods_add.setObjectName("unit_goods_add")
        self.horizontalLayout_10.addWidget(self.unit_goods_add)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_33 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_33.setMaximumSize(QtCore.QSize(180, 16777215))
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_11.addWidget(self.label_33)
        self.unitcost_goods_add = QtWidgets.QLineEdit(self.layoutWidget3)
        self.unitcost_goods_add.setMaximumSize(QtCore.QSize(200, 16777215))
        self.unitcost_goods_add.setObjectName("unitcost_goods_add")
        self.horizontalLayout_11.addWidget(self.unitcost_goods_add)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_34.setMaximumSize(QtCore.QSize(180, 16777215))
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_11.addWidget(self.label_34)
        self.price_goods_add = QtWidgets.QLineEdit(self.layoutWidget3)
        self.price_goods_add.setMaximumSize(QtCore.QSize(200, 16777215))
        self.price_goods_add.setText("")
        self.price_goods_add.setObjectName("price_goods_add")
        self.horizontalLayout_11.addWidget(self.price_goods_add)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_35 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_35.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_12.addWidget(self.label_35)
        self.supplier_goods_add = QtWidgets.QLineEdit(self.layoutWidget3)
        self.supplier_goods_add.setMaximumSize(QtCore.QSize(400, 16777215))
        self.supplier_goods_add.setFocusPolicy(QtCore.Qt.NoFocus)
        self.supplier_goods_add.setObjectName("supplier_goods_add")
        self.horizontalLayout_12.addWidget(self.supplier_goods_add)
        self.ChooseSupplier_goods_add = QtWidgets.QPushButton(self.layoutWidget3)
        self.ChooseSupplier_goods_add.setMinimumSize(QtCore.QSize(130, 0))
        self.ChooseSupplier_goods_add.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ChooseSupplier_goods_add.setObjectName("ChooseSupplier_goods_add")
        self.horizontalLayout_12.addWidget(self.ChooseSupplier_goods_add)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.submit_goods_add = QtWidgets.QPushButton(self.layoutWidget3)
        self.submit_goods_add.setMinimumSize(QtCore.QSize(130, 40))
        self.submit_goods_add.setMaximumSize(QtCore.QSize(100, 16777215))
        self.submit_goods_add.setObjectName("submit_goods_add")
        self.horizontalLayout_20.addWidget(self.submit_goods_add)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/resource/add_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Box_goods.addItem(self.tb_goods_add, icon5, "")
        self.tabWidget.addTab(self.goods, icon4, "")
        self.supplier = QtWidgets.QWidget()
        self.supplier.setObjectName("supplier")
        self.Box_supplier = QtWidgets.QToolBox(self.supplier)
        self.Box_supplier.setGeometry(QtCore.QRect(0, 0, 1031, 591))
        self.Box_supplier.setObjectName("Box_supplier")
        self.tb_supplier = QtWidgets.QWidget()
        self.tb_supplier.setGeometry(QtCore.QRect(0, 0, 1031, 521))
        self.tb_supplier.setObjectName("tb_supplier")
        self.layoutWidget_5 = QtWidgets.QWidget(self.tb_supplier)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 0, 971, 521))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_8.addWidget(self.label_36)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_13.addWidget(self.label_37)
        self.supplierid_supplier = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.supplierid_supplier.setObjectName("supplierid_supplier")
        self.horizontalLayout_13.addWidget(self.supplierid_supplier)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_13.addWidget(self.label_38)
        self.name_supplier = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.name_supplier.setObjectName("name_supplier")
        self.horizontalLayout_13.addWidget(self.name_supplier)
        self.search_supplier = QtWidgets.QPushButton(self.layoutWidget_5)
        self.search_supplier.setObjectName("search_supplier")
        self.horizontalLayout_13.addWidget(self.search_supplier)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.table_supplier = QtWidgets.QTableWidget(self.layoutWidget_5)
        self.table_supplier.setStyleSheet("QHeaderView::section {background-color:#008CBA ; /* 蓝色 */\n"
"                                                                color: WHITE;\n"
"                                                                };\n"
"                                                                text-align : center;")
        self.table_supplier.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_supplier.setObjectName("table_supplier")
        self.table_supplier.setColumnCount(6)
        self.table_supplier.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_supplier.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_supplier.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_supplier.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_supplier.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_supplier.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_supplier.setHorizontalHeaderItem(5, item)
        self.verticalLayout_8.addWidget(self.table_supplier)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/resource/supplier_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Box_supplier.addItem(self.tb_supplier, icon6, "")
        self.tb_supplier_add = QtWidgets.QWidget()
        self.tb_supplier_add.setGeometry(QtCore.QRect(0, 0, 1031, 521))
        self.tb_supplier_add.setObjectName("tb_supplier_add")
        self.layoutWidget_6 = QtWidgets.QWidget(self.tb_supplier_add)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 0, 981, 521))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_39 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_39.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_9.addWidget(self.label_39)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_40 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_40.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_14.addWidget(self.label_40)
        self.supplierid_supplier_add = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.supplierid_supplier_add.setMaximumSize(QtCore.QSize(200, 16777215))
        self.supplierid_supplier_add.setFocusPolicy(QtCore.Qt.NoFocus)
        self.supplierid_supplier_add.setObjectName("supplierid_supplier_add")
        self.horizontalLayout_14.addWidget(self.supplierid_supplier_add)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_41.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_14.addWidget(self.label_41)
        self.name_supplier_add = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.name_supplier_add.setMaximumSize(QtCore.QSize(200, 16777215))
        self.name_supplier_add.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.name_supplier_add.setObjectName("name_supplier_add")
        self.horizontalLayout_14.addWidget(self.name_supplier_add)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_42 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_42.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_15.addWidget(self.label_42)
        self.contact_supplier_add = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.contact_supplier_add.setMaximumSize(QtCore.QSize(200, 16777215))
        self.contact_supplier_add.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.contact_supplier_add.setObjectName("contact_supplier_add")
        self.horizontalLayout_15.addWidget(self.contact_supplier_add)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_43.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_15.addWidget(self.label_43)
        self.tel_supplier_add = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.tel_supplier_add.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tel_supplier_add.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tel_supplier_add.setObjectName("tel_supplier_add")
        self.horizontalLayout_15.addWidget(self.tel_supplier_add)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_44 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_44.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_16.addWidget(self.label_44)
        self.address_supplier_add = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.address_supplier_add.setMaximumSize(QtCore.QSize(500, 16777215))
        self.address_supplier_add.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.address_supplier_add.setObjectName("address_supplier_add")
        self.horizontalLayout_16.addWidget(self.address_supplier_add)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.submit_supplier_add = QtWidgets.QPushButton(self.layoutWidget_6)
        self.submit_supplier_add.setMinimumSize(QtCore.QSize(130, 40))
        self.submit_supplier_add.setMaximumSize(QtCore.QSize(100, 16777215))
        self.submit_supplier_add.setObjectName("submit_supplier_add")
        self.horizontalLayout_17.addWidget(self.submit_supplier_add)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.Box_supplier.addItem(self.tb_supplier_add, icon5, "")
        self.tabWidget.addTab(self.supplier, icon6, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(mainWindow)
        self.toolBar.setObjectName("toolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.Current_user = QtWidgets.QAction(mainWindow)
        self.Current_user.setEnabled(False)
        self.Current_user.setObjectName("Current_user")
        self.Current_department = QtWidgets.QAction(mainWindow)
        self.Current_department.setEnabled(False)
        self.Current_department.setObjectName("Current_department")
        self.exit = QtWidgets.QAction(mainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/resource/exit_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon7)
        self.exit.setVisible(True)
        self.exit.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.exit.setObjectName("exit")
        self.toolBar.addAction(self.Current_user)
        self.toolBar.addAction(self.Current_department)
        self.toolBar.addAction(self.exit)

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.Box_purchasing.setCurrentIndex(0)
        self.Box_returns.setCurrentIndex(0)
        self.Box_goods.setCurrentIndex(0)
        self.Box_supplier.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "采购部门"))
        self.label.setText(_translate("mainWindow", "采购单"))
        self.label_2.setText(_translate("mainWindow", "订单编号："))
        self.label_3.setText(_translate("mainWindow", "采购时间："))
        self.label_4.setText(_translate("mainWindow", "采购负责人："))
        self.supplier_add.setText(_translate("mainWindow", "添加供应商信息"))
        self.supplier_id.setPlaceholderText(_translate("mainWindow", "供应商编号"))
        self.label_8.setText(_translate("mainWindow", "供应商名称："))
        self.label_9.setText(_translate("mainWindow", " 供应商地址："))
        self.label_10.setText(_translate("mainWindow", "供应商联系人："))
        self.label_11.setText(_translate("mainWindow", "联系人电话："))
        item = self.table_order.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "商品编号"))
        item = self.table_order.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "商品名称"))
        item = self.table_order.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "采购数量"))
        item = self.table_order.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "商品单位"))
        item = self.table_order.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "成本单价/元"))
        item = self.table_order.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "总价/元"))
        item = self.table_order.horizontalHeaderItem(6)
        item.setText(_translate("mainWindow", "操作"))
        self.order_goods_add.setText(_translate("mainWindow", "添加商品信息"))
        self.order_submit.setText(_translate("mainWindow", "提交"))
        self.Box_purchasing.setItemText(self.Box_purchasing.indexOf(self.tb_order_2), _translate("mainWindow", "填写采购单"))
        self.label_12.setText(_translate("mainWindow", "采购单查询"))
        self.label_13.setText(_translate("mainWindow", "订单编号："))
        self.label_14.setText(_translate("mainWindow", "供应商编号："))
        self.label_15.setText(_translate("mainWindow", "订单时间："))
        self.ordertime_orderinfo.setItemText(0, _translate("mainWindow", "无"))
        self.ordertime_orderinfo.setItemText(1, _translate("mainWindow", "3天内"))
        self.ordertime_orderinfo.setItemText(2, _translate("mainWindow", "一周内"))
        self.ordertime_orderinfo.setItemText(3, _translate("mainWindow", "一个月内"))
        self.search_orderinfo.setText(_translate("mainWindow", "搜索"))
        item = self.table_orderinfo.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "采购单编号"))
        item = self.table_orderinfo.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "供应商"))
        item = self.table_orderinfo.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "负责人"))
        item = self.table_orderinfo.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "订单日期"))
        item = self.table_orderinfo.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "操作"))
        self.Box_purchasing.setItemText(self.Box_purchasing.indexOf(self.tb_order_info), _translate("mainWindow", "采购单查询"))
        self.label_21.setText(_translate("mainWindow", "暂存采购单查询"))
        self.label_22.setText(_translate("mainWindow", "订单编号："))
        self.label_23.setText(_translate("mainWindow", "供应商编号："))
        self.label_24.setText(_translate("mainWindow", "订单时间："))
        self.ordertime_draftOrder.setItemText(0, _translate("mainWindow", "无"))
        self.ordertime_draftOrder.setItemText(1, _translate("mainWindow", "3天内"))
        self.ordertime_draftOrder.setItemText(2, _translate("mainWindow", "一周内"))
        self.ordertime_draftOrder.setItemText(3, _translate("mainWindow", "一个月内"))
        self.search_draftOrder.setText(_translate("mainWindow", "搜索"))
        item = self.table_draftOrder.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "暂存采购单编号"))
        item = self.table_draftOrder.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "关联销售单编号"))
        item = self.table_draftOrder.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "商品名（ID）"))
        item = self.table_draftOrder.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "订货数量"))
        item = self.table_draftOrder.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "供应商（ID）"))
        item = self.table_draftOrder.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "负责人"))
        item = self.table_draftOrder.horizontalHeaderItem(6)
        item.setText(_translate("mainWindow", "订单日期"))
        item = self.table_draftOrder.horizontalHeaderItem(7)
        item.setText(_translate("mainWindow", "操作"))
        self.Box_purchasing.setItemText(self.Box_purchasing.indexOf(self.tb_DraftOrder), _translate("mainWindow", "暂存采购单查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.purchasing), _translate("mainWindow", "采购管理"))
        self.label_17.setText(_translate("mainWindow", "退货单"))
        self.label_18.setText(_translate("mainWindow", "退货单号："))
        self.linkbutton_return.setText(_translate("mainWindow", "关联采购单"))
        self.order_id_2.setPlaceholderText(_translate("mainWindow", "关联采购单编号"))
        self.label_19.setText(_translate("mainWindow", "退货负责人："))
        self.label_20.setText(_translate("mainWindow", "退货日期："))
        item = self.table_return.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "商品编号"))
        item = self.table_return.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "商品名称"))
        item = self.table_return.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "商品供应商"))
        item = self.table_return.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "发货数量"))
        item = self.table_return.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "商品单位"))
        item = self.table_return.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "成本单价/元"))
        item = self.table_return.horizontalHeaderItem(6)
        item.setText(_translate("mainWindow", "总价/元"))
        item = self.table_return.horizontalHeaderItem(7)
        item.setText(_translate("mainWindow", "操作"))
        self.return_button.setText(_translate("mainWindow", "提交"))
        self.Box_returns.setItemText(self.Box_returns.indexOf(self.tb_returns), _translate("mainWindow", "填写退货单"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.returns), _translate("mainWindow", "退货管理"))
        self.label_25.setText(_translate("mainWindow", "商品信息"))
        self.label_26.setText(_translate("mainWindow", "商品编号："))
        self.goodsid_goods.setPlaceholderText(_translate("mainWindow", "无"))
        self.label_27.setText(_translate("mainWindow", "商品名称："))
        self.goodsname_goods.setPlaceholderText(_translate("mainWindow", "无"))
        self.search_goods.setText(_translate("mainWindow", "搜索"))
        item = self.table_goods.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "商品编号"))
        item = self.table_goods.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "商品名称"))
        item = self.table_goods.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "商品单位"))
        item = self.table_goods.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "供应商"))
        item = self.table_goods.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "销售单价/元"))
        item = self.table_goods.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "库存数量"))
        item = self.table_goods.horizontalHeaderItem(6)
        item.setText(_translate("mainWindow", "库存单价/元"))
        item = self.table_goods.horizontalHeaderItem(7)
        item.setText(_translate("mainWindow", "操作"))
        self.Box_goods.setItemText(self.Box_goods.indexOf(self.tb_goods), _translate("mainWindow", "商品查询"))
        self.label_28.setText(_translate("mainWindow", "填写商品信息"))
        self.label_29.setText(_translate("mainWindow", "商品编号："))
        self.label_30.setText(_translate("mainWindow", "商品名称："))
        self.label_31.setText(_translate("mainWindow", "商品库存："))
        self.label_32.setText(_translate("mainWindow", "商品单位："))
        self.label_33.setText(_translate("mainWindow", "商品单位成本（元）："))
        self.label_34.setText(_translate("mainWindow", "顾客零售价（元）："))
        self.label_35.setText(_translate("mainWindow", "供应商编号："))
        self.ChooseSupplier_goods_add.setText(_translate("mainWindow", "选择供应商"))
        self.submit_goods_add.setText(_translate("mainWindow", "提交"))
        self.Box_goods.setItemText(self.Box_goods.indexOf(self.tb_goods_add), _translate("mainWindow", "添加商品信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.goods), _translate("mainWindow", "商品管理"))
        self.label_36.setText(_translate("mainWindow", "供应商信息"))
        self.label_37.setText(_translate("mainWindow", "供应商编号："))
        self.label_38.setText(_translate("mainWindow", "供应商名称:"))
        self.search_supplier.setText(_translate("mainWindow", "搜索"))
        item = self.table_supplier.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "供应商编号"))
        item = self.table_supplier.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "供应商姓名"))
        item = self.table_supplier.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "供应商联系人"))
        item = self.table_supplier.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "联系人电话"))
        item = self.table_supplier.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "供应商地址"))
        item = self.table_supplier.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "操作"))
        self.Box_supplier.setItemText(self.Box_supplier.indexOf(self.tb_supplier), _translate("mainWindow", "供应商查询"))
        self.label_39.setText(_translate("mainWindow", "填写供应商信息"))
        self.label_40.setText(_translate("mainWindow", "供应商编号："))
        self.label_41.setText(_translate("mainWindow", "供应商姓名："))
        self.label_42.setText(_translate("mainWindow", "供应商联系人: "))
        self.label_43.setText(_translate("mainWindow", "联系人电话: "))
        self.label_44.setText(_translate("mainWindow", "供应商地址: "))
        self.submit_supplier_add.setText(_translate("mainWindow", "提交"))
        self.Box_supplier.setItemText(self.Box_supplier.indexOf(self.tb_supplier_add), _translate("mainWindow", "添加供应商信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.supplier), _translate("mainWindow", "供应商管理"))
        self.label_16.setText(_translate("mainWindow", "北京邮电大学@卫闰朴"))
        self.toolBar.setWindowTitle(_translate("mainWindow", "toolBar"))
        self.Current_user.setText(_translate("mainWindow", "当前用户：xxxxx"))
        self.Current_user.setToolTip(_translate("mainWindow", "当前用户：xxxxx"))
        self.Current_department.setText(_translate("mainWindow", "当前部门：xxxxx"))
        self.exit.setText(_translate("mainWindow", "退出"))

import main_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

